/*-----------------------------------------------------------
	Furnace addons = quentid[FR]
	Addons based to mdl / entities by KoZ's : Food Mod.

	Copyright © 2015 quentid[FR] (Quentin Derpion)
	All Rights Reserved
	Steam: http://steamcommunity.com/profiles/76561198044306043
-------------------------------------------------------------*/
include("shared.lua")
function ENT:Initialize()
end
function ENT:Draw()
	self:DrawModel()
end
usermessage.Hook("indexfour", function( um )
	local indexfour = vgui.Create( "DFrame" ) 
		  indexfour:SetPos( 950,280 )
		  indexfour:SetSize( 300, 130 )
		  indexfour:SetTitle( "Four à pizza." )
		  indexfour:SetVisible( true )
		  indexfour:SetDraggable( true )
		  indexfour:ShowCloseButton( true ) 
		  indexfour:MakePopup()
			  indexfour.Paint = function()	
				draw.RoundedBox( 0, 0, 0, indexfour:GetWide(), indexfour:GetTall(), Color( 51, 122, 183, 255) )		
				draw.RoundedBox( 0, 0, 0, indexfour:GetWide(), 35, Color( 240, 173, 78, 255) )		
			  end
			 Button = vgui.Create( "DButton", indexfour )
			 Button:SetText( "Voir les recettes disponible" )
			 Button:SetTextColor( Color( 255, 255, 255,160 ) )
			 Button:SetPos( 45, 60 )
			 Button:SetSize( 200, 40 )
				 Button.Paint = function( self, w, h )
					draw.RoundedBox( 0, 0, 0, w, h, Color( 91, 192, 222, 255 ) )
				end
			Button.DoClick = function()
				if ( timer.Exists( "spawnprop1" ) ) then
					print( "Pizza au fromage." )
					indexfour:Close()
					timerspawnprop1 = vgui.Create( "DFrame" ) 
					  timerspawnprop1:SetPos( 950,280 ) 
					  timerspawnprop1:SetSize( 300, 130 ) 
					  timerspawnprop1:SetTitle( "Pizza au fromage." )
					  timerspawnprop1:SetVisible( true )
					  timerspawnprop1:SetDraggable( false ) 
					  timerspawnprop1:ShowCloseButton( false )
					  timerspawnprop1:MakePopup() 
						  timerspawnprop1.Paint = function()	
							draw.RoundedBox( 0, 0, 0, timerspawnprop1:GetWide(), timerspawnprop1:GetTall(), Color( 51, 122, 183, 255) )		
							draw.RoundedBox( 0, 0, 0, timerspawnprop1:GetWide(), 35, Color( 240, 173, 78, 255) )		
						  end
 				    DProgress  =  vgui.Create( "DProgress" ) 
					DProgress:SetPos( 1000,450 ) 
					DProgress:SetSize( 200,20 ) 
					DProgress:SetFraction( 0.45 )
					 timebut1 = vgui.Create( "DButton", timerspawnprop1 )
					 timebut1:SetText( "Fermer" )
					 timebut1:SetTextColor( Color( 255, 255, 255,160 ) )
					 timebut1:SetPos( 45, 60 )
					 timebut1:SetSize( 200, 40 )
						 timebut1.Paint = function( self, w, h )
							draw.RoundedBox( 0, 0, 0, w, h, Color( 91, 192, 222, 255 ) )
						end
					timebut1.DoClick = function()
					timerspawnprop1:Close()
					DProgress:Remove()
					end
				elseif ( timer.Exists( "spawnprop2" ) ) then
					print( "The timer spawnprop2 exists" )
					indexfour:Close()
					timerspawnprop2 = vgui.Create( "DFrame" )
					  timerspawnprop2:SetPos( 950,280 ) 
					  timerspawnprop2:SetSize( 300, 130 ) 
					  timerspawnprop2:SetTitle( "Pizza au peperonie." ) 
					  timerspawnprop2:SetVisible( true )
					  timerspawnprop2:SetDraggable( false ) 
					  timerspawnprop2:ShowCloseButton( false )
					  timerspawnprop2:MakePopup()
						  timerspawnprop2.Paint = function()	
							draw.RoundedBox( 0, 0, 0, timerspawnprop2:GetWide(), timerspawnprop2:GetTall(), Color( 51, 122, 183, 255) )		
							draw.RoundedBox( 0, 0, 0, timerspawnprop2:GetWide(), 35, Color( 240, 173, 78, 255) )		
						  end
 				    DProgress  =  vgui.Create( "DProgress" )
					DProgress:SetPos( 1000,450 ) 
					DProgress:SetSize( 200,20 ) 
					DProgress:SetFraction( 0.45 )
					 timebut2 = vgui.Create( "DButton", timerspawnprop2 )
					 timebut2:SetText( "Fermer" )
					 timebut2:SetTextColor( Color( 255, 255, 255,160 ) )
					 timebut2:SetPos( 45, 60 )
					 timebut2:SetSize( 200, 40 )
						 timebut2.Paint = function( self, w, h )
							draw.RoundedBox( 0, 0, 0, w, h, Color( 91, 192, 222, 255 ) )
						end 
					timebut2.DoClick = function()
					timerspawnprop2:Close()
					DProgress:Remove()
					end 
				else
				print( "The timer does not exist!" )
				print( "Vous regardez les recettes." )		
				print( "Addon by quentid[FR]" )
				print( "For more info contact admin@quentid.ovh" )
				indexfour:Close()
				recettefour = vgui.Create( "DFrame" )
				  recettefour:SetPos( 950,280 )
				  recettefour:SetSize( 300, 200 )
				  recettefour:SetTitle( "Four à pizza." ) 
				  recettefour:SetVisible( true )
				  recettefour:SetDraggable( true ) 
				  recettefour:ShowCloseButton( true ) 
				  recettefour:MakePopup() 
					  recettefour.Paint = function()	
						draw.RoundedBox( 0, 0, 0, recettefour:GetWide(), recettefour:GetTall(), Color( 51, 122, 183, 255) )		
						draw.RoundedBox( 0, 0, 0, recettefour:GetWide(), 35, Color( 240, 173, 78, 255) )	
					 end
				 pizzaU = vgui.Create( "DButton", recettefour )
				 pizzaU:SetText( "Pizza au Fromage" )
				 pizzaU:SetTextColor( Color( 255, 255, 255,160 ) )
				 pizzaU:SetPos( 45, 60 )
				 pizzaU:SetSize( 200, 40 )
					 pizzaU.Paint = function( self, w, h )
						draw.RoundedBox( 0, 0, 0, w, h, Color( 91, 192, 222, 255 ) )
					end
			pizzaU.DoClick = function()
			print( "Spawn entity pizza Fromage." )
			recettefour:Close()
			endfour = vgui.Create( "DFrame" ) 
				  endfour:SetPos( 950,130 ) 
				  endfour:SetSize( 300, 140 ) 
				  endfour:SetTitle( "Four à pizza." ) 
				  endfour:SetVisible( true )
				  endfour:SetDraggable( true ) 
				  endfour:ShowCloseButton( true ) 
				  endfour:MakePopup() 
					  endfour.Paint = function()	
						draw.RoundedBox( 0, 0, 0, endfour:GetWide(), endfour:GetTall(), Color( 51, 122, 183, 255) )		
						draw.RoundedBox( 0, 0, 0, endfour:GetWide(), 35, Color( 240, 173, 78, 255) )	
					 end
				closefour = vgui.Create( "DButton", endfour )
				 closefour:SetText( "Fermer le four." )
				 closefour:SetTextColor( Color( 255, 255, 255,160 ) )
				 closefour:SetPos( 45, 60 )
				 closefour:SetSize( 200, 40 )
					 closefour.Paint = function( self, w, h )
						draw.RoundedBox( 0, 0, 0, w, h, Color( 91, 192, 222, 255 ) )
					end
							closefour.DoClick = function()
							endfour:Close()
							end
				timer.Create( "spawnprop1", 20, 1, function()
				print( "La pizza est chaude!" )
					RunConsoleCommand("spawnprop1")
					net.Start( "myMessage" )
					net.WriteEntity( LocalPlayer() )
					net.SendToServer()
			 end)
			 end
				 pizzaD = vgui.Create( "DButton", recettefour )
				 pizzaD:SetText( "Pizza au Peperonie" )
				 pizzaD:SetTextColor( Color( 255, 255, 255,160 ) )
				 pizzaD:SetPos( 45, 130 )
				 pizzaD:SetSize( 200, 40 )
					 pizzaD.Paint = function( self, w, h )
						draw.RoundedBox( 0, 0, 0, w, h, Color( 91, 192, 222, 255 ) )
					end
			pizzaD.DoClick = function()
			print( "Spawn entity pizza peperonie." )
			recettefour:Close()
			endfour = vgui.Create( "DFrame" )
				  endfour:SetPos( 950,200 )
				  endfour:SetSize( 300, 140 )
				  endfour:SetTitle( "Four à pizza." )
				  endfour:SetVisible( true )
				  endfour:SetDraggable( true ) 
				  endfour:ShowCloseButton( true )
				  endfour:MakePopup()
					  endfour.Paint = function()	
						draw.RoundedBox( 0, 0, 0, endfour:GetWide(), endfour:GetTall(), Color( 51, 122, 183, 255) )		
						draw.RoundedBox( 0, 0, 0, endfour:GetWide(), 35, Color( 240, 173, 78, 255) )	
					 end
				closefour = vgui.Create( "DButton", endfour )
				 closefour:SetText( "Fermer le four." )
				 closefour:SetTextColor( Color( 255, 255, 255,160 ) )
				 closefour:SetPos( 45, 60 )
				 closefour:SetSize( 200, 40 )
					 closefour.Paint = function( self, w, h )
						draw.RoundedBox( 0, 0, 0, w, h, Color( 91, 192, 222, 255 ) )
					end
							closefour.DoClick = function()
							endfour:Close()
							end
				timer.Create( "spawnprop2", 20, 1, function()
				print( "La pizza est chaude!" )
					RunConsoleCommand("spawnprop2")
					net.Start( "myMessage" )
					net.WriteEntity( LocalPlayer() )
					net.SendToServer()
			 end)
			 end
			end 
	end 
end)